### ISSUE TITLE
Add bicycle libraries

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/cyclofix-website#12]
These are NGO-type places that offer log-term cycle rental.
See https://en.wikipedia.org/wiki/Bicycle_library
No tagging scheme available, no existing data either.
Suggested tagging:
main tag, if none available:  
* standalone: `amenity=bicycle_library` (ideal if a small private initiaitve - you don't want to show them as a community centre or bicycle shop on the general maps!)
* if part of a larger object, for example `amenity=community_centre` or `shop=bicycle` (+ add lack of sales of cycles though)n then add subtag `service:bicycle:rental=bicycle_library` or `service:bicycle:rental=library`

Relevant links:
http://fietsbieb.be/west-vlaanderen/over-fietsbieb/uitleenpunten/
https://www.fietsbieblimburg.be/
https://ruraalnetwerk.be/projecten/fietsbibliotheek

**Comment by pietervdvn** [comment]
Moved to MapComplete: https://github.com/pietervdvn/MapComplete/issues/177
