### ISSUE TITLE
differentiating between "shop=bicycle" and "amenity=bicycle_rental"

### ISSUE THREAD

**Issue by maphouse** [osmbe/cyclofix-website#15]
I have been looking for something like Cyclofix for a long time to allow people to easily (1) document/map free cycling repair services in the city of Montreal (Canada) and (2) view nearby cycling services when in an emergency!

Cyclofix does all this very well. I had some questions on the mapping controls and symbology, though.
What is the difference between the red shop symbol and the black shop symbol?
![image](https://user-images.githubusercontent.com/4475249/130273009-2a21aa6b-df59-4ccc-b182-d7d200fa30d0.png)
![image](https://user-images.githubusercontent.com/4475249/130273042-337178c2-6d97-4e8b-8142-31cb751d3872.png)
They both seem to have very similar attributes, though the dark symbols tend to have more of them... This brings me to my next point: bicycle rental services (`amenity=bicycle_rental`), which are also symbolized in red
![image](https://user-images.githubusercontent.com/4475249/130273567-c7538b9e-23f6-4806-8535-a1dfe9b0a2c7.png)

This generates much confusion (when using the map in several cities) between bicycle repair shops/boutiques and outdoor municipal rental stations like Bixi (Montreal), Citi bike (NYC), Divvy bikes (Chicago), etc. Unfortunately many OSM users map these dock locations, even though coverage is inconsistent and the dock locations change seasonally...

***Would it be possible to have a separate category in the legend for bike rental nodes?*** This would make the map much more useful, I think, for users to quickly locate repair services as opposed to more common bike rental stations!

Thanks!

**Comment by maphouse** [comment]
as a quick follow-up, I would actually suggest keeping the black symbol (and its useful add-on icons) for any bike shop.
And maybe designate the red (or another icon) as bike rental.

**Comment by pietervdvn** [comment]
Hi,

Glad that you like it!

A black symbol is a shop (thus actually selling bikes), whereas a red one does not sell bikes (but might repair or hire). 

A `amenity=bicycle_rental` which has a `network=*` tag is hidden from cyclofix. If you add a 'network' to those docks, they'll dissapear from cyclofix.

You'll probably also be interested in the [ghostbikes theme](https://mapcomplete.osm.be/ghostbikes) and the [cycle-infra](https://mapcomplete.osm.be/cycle_infra#welcome) theme (the latter one is still in beta and needs quite some improvements)

**Comment by pietervdvn** [comment]
At last: you can also create your own mapcomplete theme from scratch for whatever POI you want - as long as it fits into OSM. Have a look [at the documentation](https://github.com/pietervdvn/MapComplete/blob/master/Docs/Making_Your_Own_Theme.md)

**Comment by maphouse** [comment]
> Hi,
> 
> Glad that you like it!
> 
> A black symbol is a shop (thus actually selling bikes), whereas a red one does not sell bikes (but might repair or hire).
> 
> A `amenity=bicycle_rental` which has a `network=*` tag is hidden from cyclofix. If you add a 'network' to those docks, they'll dissapear from cyclofix.
> 
> You'll probably also be interested in the [ghostbikes theme](https://mapcomplete.osm.be/ghostbikes) and the [cycle-infra](https://mapcomplete.osm.be/cycle_infra#welcome) theme (the latter one is still in beta and needs quite some improvements)

Ah this is good to know. I'm going to add network=* to all the bike docks in my city then. that will fix it!

**Comment by maphouse** [comment]
> At last: you can also create your own mapcomplete theme from scratch for whatever POI you want - as long as it fits into OSM. Have a look [at the documentation](https://github.com/pietervdvn/MapComplete/blob/master/Docs/Making_Your_Own_Theme.md)

This is really good to know. Didn't know Cyclofix was based on a broader tool like MapComplete, which seems to handle what I found was missing from Mapcontrib (mainly the intuitive ability for map users to add data to OSM, which Mapcontrib seems to lack).

I don't think I'll need to create e new theme. I can use Cyclofix, and just adjust the legend items and location in the url, then share that url with the community. As long as people refer to the specific link, it will remain very relevant locally.

**Comment by maphouse** [comment]
> > At last: you can also create your own mapcomplete theme from scratch for whatever POI you want - as long as it fits into OSM. Have a look [at the documentation](https://github.com/pietervdvn/MapComplete/blob/master/Docs/Making_Your_Own_Theme.md)
> 
> This is really good to know. Didn't know Cyclofix was based on a broader tool like MapComplete, which seems to handle what I found was missing from Mapcontrib (mainly the intuitive ability for map users to add data to OSM, which Mapcontrib seems to lack).
> 
> I don't think I'll need to create e new theme. I can use Cyclofix, and just adjust the legend items and location in the url, then share that url with the community. As long as people refer to the specific link, it will remain very relevant locally.

Actually, if I do make my own custom map, it might just be because of language. Fr usually needs to be first here, and lang preferences don't seem to be saved in the URL like legend and loc does (this might be something worth adding!) 
I can see that when making a custom map, you can set lang options in order... which would be the only way of setting fr to the default

**Comment by pietervdvn** [comment]
> This is really good to know. Didn't know Cyclofix was based on a broader tool like MapComplete, which seems to handle what I found was missing from Mapcontrib (mainly the intuitive ability for map users to add data to OSM, which Mapcontrib seems to lack).

Which is why MapComplete was created. Note that creating your own theme isn't really polished yet.

I've added in the possibility to set the loaded language via a URL-parameter
