### ISSUE TITLE
location not requested (permanently disabled) on Android, all browsers

### ISSUE THREAD

**Issue by maphouse** [osmbe/cyclofix-website#16]
This issue seems to affect https://cyclofix.osm.be/map/, whereas https://pietervdvn.github.io/mc/develop/cyclofix.html seems to work fine.

Should users use https://pietervdvn.github.io/mc/develop/cyclofix.html ? Given that location can be stored in the url on this instance, and the app can request users' loc on mobile, it seems more useful to those outside of Brussels! The project page and Github docs might want to reflect this (point to the Github pages link, or update https://cyclofix.osm.be/map/)

Thanks!

**Comment by pietervdvn** [comment]
Hi,

The cyclofix.osm.be website is an iframe of mapcomplete. Embedding an iframe requires an explicit permission to use geolocation, [which has now been added.](https://github.com/osmbe/cyclofix-website/commit/df52c55dfd715d1fde178e4bd1ce7865b0bf9475)

mapcomplete.osm.be is the main instance of mapcomplete that everyone should use as much as possible, especially if it is linked in other websites. The mc/develop-one is the one following the develop branch and is recommended only for personal use. The audience there should be a bit more tech-savvy to report bugs back to the [mapcomplete issue tracker](https://github.com/pietervdvn/MapComplete/issues) if something goes wrong before the new version is shipped. ([You can see the split here](https://raw.githubusercontent.com/pietervdvn/MapComplete/develop/Docs/Tools/Cumulative%20changesets%20per%20host%20in%202021.png))
