### ISSUE TITLE
new icon for service:bicycle:second_hand=only

### ISSUE THREAD

**Issue by maphouse** [osmbe/cyclofix-website#17]
Rather than `service:bicycle:retail=yes` and `service:bicycle:second_hand=yes` being related to *new* and *used* bike selling respectively, `service:bicycle:retail=yes` seems to be an all-encompassing tag for any shop selling any kind of bicycle, and `service:bicycle:second_hand=only` is needed to specify that in fact the shop only sells second-hand bikes, and not new bikes.

In my option, one should not relate to the other, and something like `service:bicycle:retail_new=yes/no` and `service:bicycle:retail_second_hand=yes/no`  would be more appropriate, and would translate into statements like *this store sells new bikes* and *this store doesn't sell used bikes* for example.

__But that's beside the point__. Given the way things are, I am wondering if nodes in Cyclofix with `service:bicycle:second_hand=only` can have a different icon from the one currently used for any shop that sells bicycles.
What is now this:
![image](https://user-images.githubusercontent.com/4475249/130501279-6470381e-e9b7-42ec-905c-2afe4a04cf48.png)
Could look like this:
![image](https://user-images.githubusercontent.com/4475249/130502595-48e2a368-de31-41c6-bc25-c28f828f8e7d.png)

I'm aware it's a very picky and low-priority detail, but it really is a key question that many people have when asking about bike shops, and would help if viewed directly on the map!

**Comment by joostschouppe** [comment]
Seems like a nice addition. Could you post it at https://github.com/pietervdvn/MapComplete/issues though, as this repo is just maintaining documentation now.
