### ISSUE TITLE
save url parameters when saved to PWA/home screen (Android)

### ISSUE THREAD

**Issue by maphouse** [osmbe/cyclofix-website#18]
Would it be possible to save parameters set in the url to the PWA installed by users on their phones (when a user adds the website to their homescreen) ?

Sharing a specific URL containing loc, legend items, lang settings works great, but users lose this customization once saved to their phones or computers (oddly though, the lang setting seems to be retained, in my case).

It seems that other users (the Brussels example) get past this by putting cyclofix into an iframe containing these customizations. Is this the way I should proceed ?

**Comment by maphouse** [comment]
Along with lang, enabled geolocation is also saved by default in the Android homescreen app (which is great!), however, it doesn't autozoom to where the user is (you need to tap the geoloc symbol once for it to happen). Ideally the app should open to directly where the user is located

**Comment by maphouse** [comment]
From my perspective, these enhancements ultimately decrease the need for localized versions (iframes of cyclofix on new websites) to be created

**Comment by maphouse** [comment]
After further thought, I think the main improvement that would decrease the need for any url customization would be to make it so the map autozooms to user location. This would be a big plus.

The legend item selections aren't too big a deal, and language already gets saved. With language and location personalized, there is little need to create custom versions of cyclofix for different regions

**Comment by pietervdvn** [comment]
First of all, please report general mapcomplete issues [at the mapcomplete repository](https://github.com/pietervdvn/MapComplete/issues) - this issue tracker is more meant for the documentation on the cyclofix website, not the application itself.

> Would it be possible to save parameters set in the url to the PWA installed by users on their phones (when a user adds the website to their homescreen) ?

No, this is not possible.

> Sharing a specific URL containing loc, legend items, lang settings works great, but users lose this customization once saved to their phones or computers (oddly though, the lang setting seems to be retained, in my case).

Language gets saved in local storage, the others not.

> Along with lang, enabled geolocation is also saved by default in the Android homescreen app (which is great!), however, it doesn't autozoom to where the user is (you need to tap the geoloc symbol once for it to happen). Ideally the app should open to directly where the user is located

This has been added in the dev branch
