### ISSUE TITLE
Wrong title

### ISSUE THREAD

**Issue by comradekingu** [osmbe/cyclofix-website#20]
The website has:
Cyclofix map

For more information about the cyclofix project, go to cyclofix.osm.be.On this map, you can see, edit and add points of interest. Zoom around to see the POI ...

Which according to what I can find elsewhere should be "CycloFix".

**Comment by joostschouppe** [comment]
I'm not sure what exactly is the issue where exactly. So you mean we use both Cyclofix and CycloFix? And what page do you mean exactly?

**Comment by pietervdvn** [comment]
We are not very picky on precise branding

**Comment by comradekingu** [comment]
@joostschouppe Everywhere on https://cyclofix.osm.be/map/ including "Loading Cyclofix …".
Also https://github.com/osmbe/cyclofix-website/pull/23
Edit, and https://github.com/osmbe/cyclofix-website/pull/24

@pietervdvn Unless you have a particular penchant about also maintaining inconsistency, that sounds great :)

**Comment by pietervdvn** [comment]
This is a documentation website of a project of 3 years ago, so we are not actively maintaining it, but I did merge your PR's
