### ISSUE TITLE
Data not loading

### ISSUE THREAD

**Issue by manubrambi** [osmbe/cyclofix-website#21]
Hello!
It seems the data is not loading anymore. If I open the map I get an infinite "Loading data..." screen
![image](https://user-images.githubusercontent.com/33860654/219398740-2a76e488-bf38-473d-8d08-8fe322290682.png)

Thanks and keep up the good work!

**Comment by pietervdvn** [comment]
It just takes a while to load if you want to load everything in Brussels.

This is a duplicate of https://github.com/pietervdvn/MapComplete/issues/1183
