### ISSUE TITLE
updated links to docs not reflected on website

### ISSUE THREAD

**Issue by maphouse** [osmbe/cyclofix-website#22]
These changes https://github.com/osmbe/cyclofix-website/commit/84c7b41ac15a74cb3628855b39b68d446e2eb534
Are not visible on https://cyclofix.osm.be/docs/using-data-map/

**Comment by joostschouppe** [comment]
That's weird, because https://github.com/osmbe/cyclofix-website/blob/master/content/docs/using-data-map.md is up to date. Perhaps the website needs to be manually deployed @ubipo @pietervdvn ?

**Comment by pietervdvn** [comment]
Turns out that the build process broke in the meantime; I've fixed it and the links are now properly updated.

Thanks for spotting this!
