### ISSUE TITLE
add-image-only mode

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/cyclofix-website#3]
User story:
- I am somewhere
- I see something fun
- but there is no suitable mapcomplete instance
- so I go to the mapcomplete-image-add-machine
- I say "I am here" and it just returns all OSM data within a 10 meter radius
- I click on the thingy I want to add a picture for and I add my picture

**Comment by pietervdvn** [comment]
This is actually better discussed at the mapcomplete repo, but...

This is difficult to present easily to the users. A layer with e.g. amenity=*/tourism=*/... is possible, but very hard to have in a user-friendly way.
