### ISSUE TITLE
Subscribe to certain map changes

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/cyclofix-website#5]
Question from cyclo
First thought: IFTTT, but not diretcly linkeable from Overpass
Not available in the default RSS services
Found this: https://wiki.openstreetmap.org/wiki/Osm-watch (after googling overpass + rss) , but it's dead
Relevant query: http://overpass-turbo.eu/s/WAX
Relevant CSV query: http://overpass-turbo.eu/s/WAY

**Comment by ghost** [comment]
Should be possible to, for example, let the owner of public pumps know when a pump is declared as broken (cf. RSS, ifttt)

**Comment by pietervdvn** [comment]
Osoc project for next year: notify people/municipalities of changes in OSM ;)

**Comment by pietervdvn** [comment]
Closing as this is a wider issue within OSM, services such as OsmCha or whodiddit should be used instead of providing this via cyclofix/mapcomplete
