### ISSUE TITLE
Longlist data to add

### ISSUE THREAD

**Issue by ghost** [osmbe/cyclofix-website#6]
Icon needed:
- cycle transport office (like "freight company", but with bike)
- bike cafés https://github.com/osmbe/cyclofix-docs/issues/10#issuecomment-664247954
- bicycle advocacy office (e.g. https://www.provelo.org/en ; https://ecf.com/ ) 
https://github.com/osmbe/cyclofix-docs/issues/10#issuecomment-664251076 , bike tours and clubs  (eg http://kring.cc/) https://github.com/osmbe/cyclofix-docs/issues/10#issuecomment-664251076

Just extend query:
- buy a second hand bike https://github.com/osmbe/cyclofix-docs/issues/10#issuecomment-664248990
- fix your own bike https://github.com/osmbe/cyclofix-docs/issues/10#issuecomment-664246084
- rent a bike https://github.com/osmbe/cyclofix-docs/issues/10#issuecomment-664251895

Ignore for now
- ~~public bicycle charging stations (apparently lidl bxl and ikea anderlecht)~~
- traffic lights (exception for cyclists)
- parking (paid/premium)
- cycle lanes

- in MVP: category 'other' and 'other places with pumps' > should we specify these more?

**Comment by pietervdvn** [comment]
Is this bicycle repair station still operational?

**Comment by pietervdvn** [comment]
Does this shop sell _electrical_ bikes (yes, no, only, limited, pedelec)

**Comment by joostschouppe** [comment]
## fix your own bike

This can be associated with a large number of different types of objects

* a bicycle repair shop where you can work on it yourself > `service:bicycle:diy=yes`
* a place where they teach you to fix your bike while you do it > proposed: `service:bicycle:diy=yes + service:bicycle:diy:training=yes`

Ignore these:
* a place where they formally teach you to fix your bicycle: `education_profile:bicycle_repair=yes`
* a place where some groups sometimes happens to go to give a workshop about fixing bikes `> poor fit for osm!`

**Comment by joostschouppe** [comment]
# Bike café
`amenity=pub OR
amenity=cafe`
AND one OR more of the below
`club=cycling`
`service:bicycle:*=yes`
`pub=cycling`

**Comment by joostschouppe** [comment]
## Second hand bikes
Any object with `service:bicycle:second_hand=yes`

**Comment by joostschouppe** [comment]
## Bike tours,  clubs and advocacy
From https://wiki.openstreetmap.org/wiki/Bicycle#Bicycle_Clubs_.26_Associations
 
### Community centers focused on cycling
_A meeting place for cyclists with activities like self repair bicycle worshop, cartoparty, expositions, meetings, ..., can be map with:_

```
amenity=community_centre
community_centre=club_house [optional]
club=bicycle
```

Maybe include operator:type=cooperative to filter out coops like shown here: http://cycloperativa.org/carte.html

### a bicycle association with few or no public service at that place

```
office=association
association=bicycle
```
(eg main office of Cyclo, Fietsersbond)



### For a cycling sport club:

```
club=sport
sport=cycling 
```

**Comment by joostschouppe** [comment]
## Bicycle rental

`amenity=bicycle_rental + !network=*`
OR
`service:bicycle:rental=yes`

NOTE: there are no separate bicycle rental places in Brussels

**Comment by pietervdvn** [comment]
- Cycle transport office: I'm not gonna add those
- Bike cafés: check
- Advocacy office: check (in the bicycle themed object layer)
- extra tagging (buy, fix, rent): check
- charging: there is a separate mapcomplete theme for that;  also see https://github.com/pietervdvn/MapComplete/issues/178
- traffic lights: out of scope
- parking: done
- cycling lanes: out of scope
- The 'other'-layer is growing organically
- Repair station operational: check
- Second hand: check
- Bike tours: out of scope
- clubs: added in cycling-themed-objects
- advocacy: added in cycling-themed-objects
- bicycle:rental: out of scope
