### ISSUE TITLE
Deploy on cyclofix.bike.brussels

### ISSUE THREAD

**Issue by pietervdvn** [osmbe/cyclofix-website#7]

**Comment by pietervdvn** [comment]
And maybe also on osm.be?

**Comment by joostschouppe** [comment]
So mapcomplete.osm.be/cyclofix? :)

**Comment by joostschouppe** [comment]
Pieter F sent a mail to web@sprb.brussels and owauters

**Comment by pietervdvn** [comment]
> So mapcomplete.osm.be/cyclofix? :)

Well, this one is up ;)

As bike.brussels isn't too responsive, I'm gonna give up on this issue. And [De Fietsambassade Gent](https://fietsambassade.gent.be/nl/herstel-en-onderhoud/een-fietspomp-jouw-buurt) and [cyclo.org](https://www.cyclo.org/nl/nieuws/pump-it-yourself-%21) are pretty cool too!
